### ISSUE TITLE
Question for Motion feature

### ISSUE THREAD

**Issue by bryeartem** [andrey-kondratov/juancamera-proxy#4]
Is there any chance you would know how to get a motion event from this camera?  I am trying to integrate a Night Owl WNIP-2LTA which seems to be a Juan Intelligent camera but it seems no one else has really dug into these at all like you have.  I am just looking for a response from like a curl command or something when motion has been detected.  Thanks, sorry if not the right way to go about this I am just at a loss with these cameras other than the snapshot/rtsp stream.

**Comment by andrey-kondratov** [comment]
No, sorry, but I haven't been able to find anything this advanced

**Comment by bryeartem** [comment]
Thank you.
